project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Final Heartlime Book"
  subtitle: "Model Interpretation with LIME and IML"
  author:
    - Jiangnan Wan (jw4638)
    - Jinglei Lou (jl6954)
  repo-url: https://github.com/Ceeecilllia/final-heartlime-book
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - models.qmd
    - tree_model.qmd
    - rf_model.qmd
    - svm_model.qmd
    - nn_model.qmd
    - logistic_model.qmd
    - lime_analysis.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true
